---
# tasks file for os_standard

- name: configure hosts file
  blockinfile:
    path: /etc/hosts
    marker: "###{mark} LAB MINI HOSTS ###"
    block: |
      {% for host in play_hosts %}
      {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host + '.marekexample.com' }} {{ host }}
      {% endfor %}


- name: set hostname
  shell: hostnamectl set-hostname --static {{ inventory_hostname }}.marekexample.com

- name: install necessary packages
  dnf:
    name: "{{ linux_packages }}"

- name: Set timezone 
  community.general.timezone:
    name: Europe/Warsaw


- name: enable NTP
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
    masked: no

- name: add devops group
  group:
    name: devops
    state: present
    gid: 1100

- name: add automation group
  group:
    name: automation
    state: present
    gid: 1101

- name: add automation user
  user:
    name: automation
    comment: 'Automation account'
    uid: 1101
    shell: /bin/bash
    group: automation
    password: "{{ secret_vars.ssh_password | string | password_hash('sha512')}}"
    groups: devops
    append: yes

- name: deploy ansible user authorized key
  authorized_key:
    user: automation
    state: present
    key: "{{ lookup('file', '../../../vault_id_rsa_mini_automation.pub') }}"


- name: deploy sudo for devops group
  copy:
    content: '%devops   ALL=(ALL)       NOPASSWD: ALL'
    dest: /etc/sudoers.d/10-devops
    mode: '0644'
    validate: /usr/sbin/visudo -csf %s

- name: add node_exporter group
  group:
    name: node_exporter
    state: present
    gid: 1102

- name: install node_exporter for prometheus
  user:
    name: node_exporter
    comment: 'Node Exporter for Prometheus'
    uid: 1102
    shell: /bin/false
    group: node_exporter 
    system: yes
    create_home: no

- name: download node exporter binary
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp

- name: unarchive node exporter binary
  unarchive:
    src: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: copy node_exporter binary
  copy:
    src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    owner: node_exporter
    group: node_exporter
    mode: '0555'

- name: copy node_exporter systemd
  copy:
    src: node_exporter/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: start node_exporter
  systemd:
    name: node_exporter
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: enable firewalld
  firewalld:
    port: 9100/tcp
    permanent: yes
    state: enabled
    immediate: yes
  ignore_errors: yes

