install_webserver:
    stage: build
    script:
        - sudo dnf install -y httpd
        - sudo firewall-cmd --add-service=http --permanent
        - sudo firewall-cmd --reload
        - sudo systemctl enable --now httpd
deploy_www_content:
    stage: deploy
    script:
        - echo 'pipeline result <b>v002<b>' | sudo tee  /var/www/html/index.html