install_webserver:
    stage: build
    script:
        - sudo dnf install -y httpd
        - sudo firewall-cmd --add-service=httpd --permanent
        - sudo firewall-cmd --reload
        - sudo systemctl enable --now httpd
deploy_www_content:
    stage: deploy
    script:
        - sudo echo "pipeline result v001" > /var/www/html/index.html