include:
  - local: /pipelines/templates/webserver_extended.yml
    rules:
      - if: $PIPELINE_ACTION == "webserver_extended"
  - local: /pipelines/templates/webserver_simple.yml
    rules:
      - if: $PIPELINE_ACTION == "webserver_simple"

stages:
    - build
    - deploy
    - test

job:
  script:
    - echo "executing pipeline $PIPELINE_ACTION"
