variables:
    MY_MESSAGE: 
        value: "custom message"
        description: "a simple comment"
    MY_ENVIRONMENT: 
        value: "tst"
        description: "a simple comment"

stages:
    - build
    - deploy
    - test


install_webserver:
    stage: build
    before_script:
        - eval $(ssh-agent -s)
        - echo "$SSH_AUTOMATION_PRIVKEY" | tr -d '\r' | ssh-add -
        - mkdir ~/.ssh -p
        - chmod 700 ~/.ssh
        - ssh-keyscan $VM_HOSTNAME >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - ssh $SSH_AUTOMATION_USER@$VM_IPADDRESS "hostname && echo 'Welcome!!!' > welcome.txt"
deploy_www_content:
    stage: deploy
    script:
        - echo 'pipeline result <b>v002</b><p>' | sudo tee  /var/www/html/index.html
        - echo "<i>$MY_MESSAGE</i><p>" | sudo tee -a /var/www/html/index.html
        - echo "<i>environment $MY_ENVIRONMENT</i>" | sudo tee -a /var/www/html/index.html
        - echo "for project $CI_PROJECT_NAME by $CI_RUNNER_DESCRIPTION at $CI_PIPELINE_CREATED_AT<p>" | sudo tee -a /var/www/html/index.html
        - echo "hosted on $GITLAB_PLATFORM" | sudo tee -a /var/www/html/index.html
test_www:
    stage: test
    script:
        - curl -s -k http://runner.marekexample.com | grep "$MY_MESSAGE"