include:
  - local: /pipelines/templates/webserver_extended.yml
    rules:
      - if: $PIPELINE_ACTION == "webserver_extended"
  - local: /pipelines/templates/webserver_simple.yml
    rules:
      - if: $PIPELINE_ACTION == "webserver_simple"
  - local: /pipelines/templates/certificate_genenerate.yml
    rules:
      - if: $PIPELINE_ACTION == "generate_certificate"

#stages:
#- build
#   - deploy
#   - test

job:
  script:
    - echo "executing pipeline $PIPELINE_ACTION"
