---
# tasks file for workstation
# install python
# install ssh key configuration
#
#
#
- name: install necessary packages
  package:
    name: "{{ linux_packages }}"
  delegate_to: localhost
  run_once: yes

- name: configure env vars in bashrc file
  blockinfile:
    path: ~/.bashrc
    marker: "###{mark} LAB MINI ENV VARS ###"
    block: |

      {% for item in (secret_vars | dict2items ) %}
      export {{ item.key | upper }}={{ item.value }}
      {% endfor %}


  become: false
  delegate_to: localhost
  run_once: yes
- name: configure hosts file
  blockinfile:
    path: /etc/hosts
    marker: "###{mark} LAB MINI HOSTS ###"
    block: |

      {% for host in play_hosts %}
      {{ hostvars[host]['ansible_host']}} {{ host + '.marekexample.com' }} {{ host }}
      {% endfor %}

  delegate_to: localhost
  run_once: yes


- name: install pip requirements
  shell: pip install -r requirements.txt
  become: false
  delegate_to: localhost
  run_once: yes

- name: get list of hosts
  debug:
    msg: |
      Host {% for host in play_hosts -%}
      {{ host }} {{ host + '.marekexample.com '}}
       {%- endfor %}

        User automation
        IdentityFile ~/.ssh/id_rsa_lab_mini
  become: false      
  run_once: yes
  register: my_inventory

- name: copy ssh key file
  copy:
    content: "{{ lookup('file', '../../../vault_id_rsa_mini_automation') }}\n"
    dest: ~/.ssh/id_rsa_lab_mini
    mode: '0600'
  become: false
  delegate_to: localhost
  run_once: yes

- name: configure ssh client
  blockinfile:
    path: ~/.ssh/config
    marker: "###{mark} LAB MINI SSH CONFIG ###"
    block: |
      {{ my_inventory.msg }}
  become: false
  delegate_to: localhost
  run_once: yes
