- name: downlaod runner binary
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    dest: /usr/local/bin/gitlab-runner
    mode: '0555'

- name: Add runner user
  ansible.builtin.user:
    name: gitlab-runner
    comment: GitLab Runner
    shell: /bin/bash
    create_home: yes

- name: configure runner
  raw: >
     gitlab-runner stop  ;
     openssl s_client -connect gitlab.marekexample.com:443 -showcerts </dev/null 2>/dev/null | sed -e '/-----BEGIN/,/-----END/!d' | sudo tee /tmp/gitlab.marekexample.com.crt >/dev/null ;
     rm -f /etc/systemd/system/gitlab-runner.service ;

- name: configure runner install
  raw: >
     gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner ;
     gitlab-runner start

- name: configure runner 2
  raw: >
     gitlab-runner register --non-interactive --run-untagged --name runner.marekexample.com --url https://gitlab.marekexample.com/ --tls-ca-file=/tmp/gitlab.marekexample.com.crt --executor shell --tag-list vm,linux,server --registration-token {{ gitlab_runner_registration_token }}


