---
# tasks file for gitlab_runner

- name: download file
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh
    dest: /tmp/script.rpm.sh
    mode: '0550'

- name: run installer
  shell: /tmp/script.rpm.sh

- name: install runner
  dnf:
    name: gitlab-runner
    state: latest
