FROM alpine:latest

RUN apk update; apk add --no-cache openssl easy-rsa bash apache2
RUN rm -f /var/www/localhost/htdocs/index.html
RUN ln -s /files-marekexample /var/www/localhost/htdocs/files-marekexample
EXPOSE 80
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
#CMD ln -s /usr/share/easy-rsa /easy-rsa
#CMD /usr/share/easy-rsa/easyrsa init-pki
#CMD /usr/share/easy-rsa/easyrsa build-ca nopass
