global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['gitlab.marekexample.com:9100']
    - targets: ['prod1.marekexample.com:9100']
    - targets: ['tst1.marekexample.com:9100']
    - targets: ['runner.marekexample.com:9100']
    - targets: ['devops.marekexample.com:9100']
    - targets: ['k8-master1.marekexample.com:9100']
    - targets: ['k8-worker1.marekexample.com:9100']
    - targets: ['k8-worker2.marekexample.com:9100']


  - job_name: 'vmware_vcenter'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['devops.marekexample.com:9272']
