global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['192.168.0.106:9100']
    - targets: ['192.168.0.107:9100']
    - targets: ['192.168.0.108:9100']
    - targets: ['192.168.0.109:9100']
    - targets: ['192.168.0.110:9100']
