---
# tasks file for devops
#
- name: prepare devops root dir
  file:
    path: /devops
    state: directory
    mode: '0775'


- name: deploy apps configurations
  synchronize:
    src: devops
    dest: / 

- name: restart docker-compose prometheus-grafana
  shell: /usr/local/bin/docker-compose -f /devops/prometheus-grafana/docker-compose.yml restart
