---
# tasks file for devops
#
- name: configure env vars in bashrc file
  blockinfile:
    path: ~/.bashrc
    marker: "###{mark} LAB MINI ENV VARS ###"
    block: |

      {% for item in (secret_vars | dict2items ) %}
      export {{ item.key | upper }}={{ item.value }}
      {% endfor %}

- name: prepare devops root dir
  file:
    path: /devops
    state: directory
    mode: '0775'


- name: deploy apps configurations
  synchronize:
    src: devops
    dest: / 

- name: start docker-compose 
  shell: /usr/local/bin/docker-compose -f /devops/{{ item }}/docker-compose.yml up -d
  loop:
    - prometheus-grafana
    - hashicorp-vault
    - elk


- name: restart docker-compose
  shell: /usr/local/bin/docker-compose -f /devops/{{ item }}/docker-compose.yml restart
  loop:
    - prometheus-grafana
    - hashicorp-vault
    - elk
