---
# tasks file for devops
#
- name: configure env vars in bashrc file
  blockinfile:
    path: ~/.bashrc
    marker: "###{mark} LAB MINI ENV VARS ###"
    block: |

      {% for item in (secret_vars | dict2items ) %}
      export {{ item.key | upper }}={{ item.value }}
      {% endfor %}

- name: stop docker-compose apps
  shell: /usr/local/bin/docker-compose -f /devops/{{ item }}/docker-compose.yml down
  loop:
    - prometheus-grafana
    - hashicorp-vault
    - elk
    - ca-marekexample


- name: remove custom containers
  shell: docker rm -f {{ item }}
  loop:
    - ca-marekexample-ca-marekexample-1

- name: prepare devops root dir
  file:
    path: /devops
    state: directory
    mode: '0775'


- name: deploy apps configurations
  copy:
    src: devops
    dest: / 
    decrypt: yes


- name: rebuild custom containers
  shell: /usr/local/bin/docker-compose -f /devops/{{ item }}/docker-compose.yml build
  loop:
    - ca-marekexample

- name: start apps
  shell: /usr/local/bin/docker-compose -f /devops/{{ item }}/docker-compose.yml up -d
  loop:
    - prometheus-grafana
    - hashicorp-vault
    - elk
    - ca-marekexample
